// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: totle_tasks/v1/totle_tasks.proto

package totletasksv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoalService_CreateGoal_FullMethodName = "/totle_tasks.v1.GoalService/CreateGoal"
	GoalService_GetGoal_FullMethodName    = "/totle_tasks.v1.GoalService/GetGoal"
	GoalService_ListGoals_FullMethodName  = "/totle_tasks.v1.GoalService/ListGoals"
	GoalService_UpdateGoal_FullMethodName = "/totle_tasks.v1.GoalService/UpdateGoal"
	GoalService_DeleteGoal_FullMethodName = "/totle_tasks.v1.GoalService/DeleteGoal"
)

// GoalServiceClient is the client API for GoalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GoalService manages individual user objectives and CRUD operations for goal tracking.
type GoalServiceClient interface {
	// GoalService.CreateGoal creates a new Goal for the authenticated user.
	CreateGoal(ctx context.Context, in *CreateGoalRequest, opts ...grpc.CallOption) (*CreateGoalResponse, error)
	// GoalService.GetGoal retrieves a specific Goal by its unique resource name.
	GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error)
	// GoalService.ListGoals returns a paginated list of Goals belonging to the parent resource.
	ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error)
	// GoalService.UpdateGoal updates specific fields of an existing Goal using a FieldMask.
	UpdateGoal(ctx context.Context, in *UpdateGoalRequest, opts ...grpc.CallOption) (*UpdateGoalResponse, error)
	// GoalService.DeleteGoal permanently removes a Goal from the system.
	DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*DeleteGoalResponse, error)
}

type goalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoalServiceClient(cc grpc.ClientConnInterface) GoalServiceClient {
	return &goalServiceClient{cc}
}

func (c *goalServiceClient) CreateGoal(ctx context.Context, in *CreateGoalRequest, opts ...grpc.CallOption) (*CreateGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGoalResponse)
	err := c.cc.Invoke(ctx, GoalService_CreateGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoalResponse)
	err := c.cc.Invoke(ctx, GoalService_GetGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGoalsResponse)
	err := c.cc.Invoke(ctx, GoalService_ListGoals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) UpdateGoal(ctx context.Context, in *UpdateGoalRequest, opts ...grpc.CallOption) (*UpdateGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoalResponse)
	err := c.cc.Invoke(ctx, GoalService_UpdateGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*DeleteGoalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGoalResponse)
	err := c.cc.Invoke(ctx, GoalService_DeleteGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoalServiceServer is the server API for GoalService service.
// All implementations must embed UnimplementedGoalServiceServer
// for forward compatibility.
//
// GoalService manages individual user objectives and CRUD operations for goal tracking.
type GoalServiceServer interface {
	// GoalService.CreateGoal creates a new Goal for the authenticated user.
	CreateGoal(context.Context, *CreateGoalRequest) (*CreateGoalResponse, error)
	// GoalService.GetGoal retrieves a specific Goal by its unique resource name.
	GetGoal(context.Context, *GetGoalRequest) (*GetGoalResponse, error)
	// GoalService.ListGoals returns a paginated list of Goals belonging to the parent resource.
	ListGoals(context.Context, *ListGoalsRequest) (*ListGoalsResponse, error)
	// GoalService.UpdateGoal updates specific fields of an existing Goal using a FieldMask.
	UpdateGoal(context.Context, *UpdateGoalRequest) (*UpdateGoalResponse, error)
	// GoalService.DeleteGoal permanently removes a Goal from the system.
	DeleteGoal(context.Context, *DeleteGoalRequest) (*DeleteGoalResponse, error)
	mustEmbedUnimplementedGoalServiceServer()
}

// UnimplementedGoalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoalServiceServer struct{}

func (UnimplementedGoalServiceServer) CreateGoal(context.Context, *CreateGoalRequest) (*CreateGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoal not implemented")
}
func (UnimplementedGoalServiceServer) GetGoal(context.Context, *GetGoalRequest) (*GetGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoal not implemented")
}
func (UnimplementedGoalServiceServer) ListGoals(context.Context, *ListGoalsRequest) (*ListGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGoals not implemented")
}
func (UnimplementedGoalServiceServer) UpdateGoal(context.Context, *UpdateGoalRequest) (*UpdateGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoal not implemented")
}
func (UnimplementedGoalServiceServer) DeleteGoal(context.Context, *DeleteGoalRequest) (*DeleteGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoal not implemented")
}
func (UnimplementedGoalServiceServer) mustEmbedUnimplementedGoalServiceServer() {}
func (UnimplementedGoalServiceServer) testEmbeddedByValue()                     {}

// UnsafeGoalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoalServiceServer will
// result in compilation errors.
type UnsafeGoalServiceServer interface {
	mustEmbedUnimplementedGoalServiceServer()
}

func RegisterGoalServiceServer(s grpc.ServiceRegistrar, srv GoalServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoalService_ServiceDesc, srv)
}

func _GoalService_CreateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).CreateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_CreateGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).CreateGoal(ctx, req.(*CreateGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_GetGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetGoal(ctx, req.(*GetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_ListGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).ListGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_ListGoals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).ListGoals(ctx, req.(*ListGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_UpdateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).UpdateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_UpdateGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).UpdateGoal(ctx, req.(*UpdateGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_DeleteGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).DeleteGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_DeleteGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).DeleteGoal(ctx, req.(*DeleteGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoalService_ServiceDesc is the grpc.ServiceDesc for GoalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "totle_tasks.v1.GoalService",
	HandlerType: (*GoalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGoal",
			Handler:    _GoalService_CreateGoal_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _GoalService_GetGoal_Handler,
		},
		{
			MethodName: "ListGoals",
			Handler:    _GoalService_ListGoals_Handler,
		},
		{
			MethodName: "UpdateGoal",
			Handler:    _GoalService_UpdateGoal_Handler,
		},
		{
			MethodName: "DeleteGoal",
			Handler:    _GoalService_DeleteGoal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "totle_tasks/v1/totle_tasks.proto",
}

const (
	BingoService_GetBingoCard_FullMethodName    = "/totle_tasks.v1.BingoService/GetBingoCard"
	BingoService_UpdateBingoCard_FullMethodName = "/totle_tasks.v1.BingoService/UpdateBingoCard"
)

// BingoServiceClient is the client API for BingoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BingoService manages the gamified Bingo Card view of goals, organized by time periods.
type BingoServiceClient interface {
	// BingoService.GetBingoCard retrieves the bingo card for a specific year and month.
	GetBingoCard(ctx context.Context, in *GetBingoCardRequest, opts ...grpc.CallOption) (*GetBingoCardResponse, error)
	// BingoService.UpdateBingoCard updates the layout or goal assignments within a bingo card.
	UpdateBingoCard(ctx context.Context, in *UpdateBingoCardRequest, opts ...grpc.CallOption) (*UpdateBingoCardResponse, error)
}

type bingoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBingoServiceClient(cc grpc.ClientConnInterface) BingoServiceClient {
	return &bingoServiceClient{cc}
}

func (c *bingoServiceClient) GetBingoCard(ctx context.Context, in *GetBingoCardRequest, opts ...grpc.CallOption) (*GetBingoCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBingoCardResponse)
	err := c.cc.Invoke(ctx, BingoService_GetBingoCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bingoServiceClient) UpdateBingoCard(ctx context.Context, in *UpdateBingoCardRequest, opts ...grpc.CallOption) (*UpdateBingoCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBingoCardResponse)
	err := c.cc.Invoke(ctx, BingoService_UpdateBingoCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BingoServiceServer is the server API for BingoService service.
// All implementations must embed UnimplementedBingoServiceServer
// for forward compatibility.
//
// BingoService manages the gamified Bingo Card view of goals, organized by time periods.
type BingoServiceServer interface {
	// BingoService.GetBingoCard retrieves the bingo card for a specific year and month.
	GetBingoCard(context.Context, *GetBingoCardRequest) (*GetBingoCardResponse, error)
	// BingoService.UpdateBingoCard updates the layout or goal assignments within a bingo card.
	UpdateBingoCard(context.Context, *UpdateBingoCardRequest) (*UpdateBingoCardResponse, error)
	mustEmbedUnimplementedBingoServiceServer()
}

// UnimplementedBingoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBingoServiceServer struct{}

func (UnimplementedBingoServiceServer) GetBingoCard(context.Context, *GetBingoCardRequest) (*GetBingoCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBingoCard not implemented")
}
func (UnimplementedBingoServiceServer) UpdateBingoCard(context.Context, *UpdateBingoCardRequest) (*UpdateBingoCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBingoCard not implemented")
}
func (UnimplementedBingoServiceServer) mustEmbedUnimplementedBingoServiceServer() {}
func (UnimplementedBingoServiceServer) testEmbeddedByValue()                      {}

// UnsafeBingoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BingoServiceServer will
// result in compilation errors.
type UnsafeBingoServiceServer interface {
	mustEmbedUnimplementedBingoServiceServer()
}

func RegisterBingoServiceServer(s grpc.ServiceRegistrar, srv BingoServiceServer) {
	// If the following call pancis, it indicates UnimplementedBingoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BingoService_ServiceDesc, srv)
}

func _BingoService_GetBingoCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBingoCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingoServiceServer).GetBingoCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BingoService_GetBingoCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingoServiceServer).GetBingoCard(ctx, req.(*GetBingoCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BingoService_UpdateBingoCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBingoCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingoServiceServer).UpdateBingoCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BingoService_UpdateBingoCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingoServiceServer).UpdateBingoCard(ctx, req.(*UpdateBingoCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BingoService_ServiceDesc is the grpc.ServiceDesc for BingoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BingoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "totle_tasks.v1.BingoService",
	HandlerType: (*BingoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBingoCard",
			Handler:    _BingoService_GetBingoCard_Handler,
		},
		{
			MethodName: "UpdateBingoCard",
			Handler:    _BingoService_UpdateBingoCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "totle_tasks/v1/totle_tasks.proto",
}
