// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: totle_tasks/v1/totle_tasks.proto

package totletasksv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Goal.Visibility defines the privacy levels allowed for this resource.
type Goal_Visibility int32

const (
	Goal_VISIBILITY_UNSPECIFIED Goal_Visibility = 0
	Goal_VISIBILITY_PRIVATE     Goal_Visibility = 1 // Only the owner.
	Goal_VISIBILITY_FRIENDS     Goal_Visibility = 2 // Visible to accepted friends.
	Goal_VISIBILITY_PUBLIC      Goal_Visibility = 3 // Visible to the community.
)

// Enum value maps for Goal_Visibility.
var (
	Goal_Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PRIVATE",
		2: "VISIBILITY_FRIENDS",
		3: "VISIBILITY_PUBLIC",
	}
	Goal_Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PRIVATE":     1,
		"VISIBILITY_FRIENDS":     2,
		"VISIBILITY_PUBLIC":      3,
	}
)

func (x Goal_Visibility) Enum() *Goal_Visibility {
	p := new(Goal_Visibility)
	*p = x
	return p
}

func (x Goal_Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Goal_Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_totle_tasks_v1_totle_tasks_proto_enumTypes[0].Descriptor()
}

func (Goal_Visibility) Type() protoreflect.EnumType {
	return &file_totle_tasks_v1_totle_tasks_proto_enumTypes[0]
}

func (x Goal_Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Goal_Visibility.Descriptor instead.
func (Goal_Visibility) EnumDescriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{0, 0}
}

// GetBingoCardRequest.BingoCardView controls the level of detail returned.
type GetBingoCardRequest_BingoCardView int32

const (
	GetBingoCardRequest_BINGO_CARD_VIEW_UNSPECIFIED GetBingoCardRequest_BingoCardView = 0
	// BINGO_CARD_VIEW_BASIC returns the grid with only goal resource names.
	GetBingoCardRequest_BINGO_CARD_VIEW_BASIC GetBingoCardRequest_BingoCardView = 1
	// BINGO_CARD_VIEW_FULL returns the grid with goal_value objects fully populated.
	GetBingoCardRequest_BINGO_CARD_VIEW_FULL GetBingoCardRequest_BingoCardView = 2
)

// Enum value maps for GetBingoCardRequest_BingoCardView.
var (
	GetBingoCardRequest_BingoCardView_name = map[int32]string{
		0: "BINGO_CARD_VIEW_UNSPECIFIED",
		1: "BINGO_CARD_VIEW_BASIC",
		2: "BINGO_CARD_VIEW_FULL",
	}
	GetBingoCardRequest_BingoCardView_value = map[string]int32{
		"BINGO_CARD_VIEW_UNSPECIFIED": 0,
		"BINGO_CARD_VIEW_BASIC":       1,
		"BINGO_CARD_VIEW_FULL":        2,
	}
)

func (x GetBingoCardRequest_BingoCardView) Enum() *GetBingoCardRequest_BingoCardView {
	p := new(GetBingoCardRequest_BingoCardView)
	*p = x
	return p
}

func (x GetBingoCardRequest_BingoCardView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBingoCardRequest_BingoCardView) Descriptor() protoreflect.EnumDescriptor {
	return file_totle_tasks_v1_totle_tasks_proto_enumTypes[1].Descriptor()
}

func (GetBingoCardRequest_BingoCardView) Type() protoreflect.EnumType {
	return &file_totle_tasks_v1_totle_tasks_proto_enumTypes[1]
}

func (x GetBingoCardRequest_BingoCardView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetBingoCardRequest_BingoCardView.Descriptor instead.
func (GetBingoCardRequest_BingoCardView) EnumDescriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{4, 0}
}

// Goal represents a single task or objective a user wants to track.
type Goal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Goal.name is the unique resource name of the goal. Format: goals/{goal}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Goal.title is the user-visible title or description of the goal.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Goal.completed is the status indicating if the goal has been achieved.
	Completed bool `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Goal.is_assigned indicates if this goal is currently placed on a BingoCard.
	IsAssigned bool `protobuf:"varint,4,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	// Goal.visibility determines who can see this goal in social contexts.
	Visibility Goal_Visibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=totle_tasks.v1.Goal_Visibility" json:"visibility,omitempty"`
	// Goal.is_archived indicates if the goal has been soft-deleted (is_active = false).
	// Archived goals remain in the system to preserve Bingo history.
	IsArchived bool `protobuf:"varint,6,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	// Goal.create_time is the timestamp when the goal was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Goal.update_time is the timestamp when the goal was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Goal) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Goal) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

func (x *Goal) GetVisibility() Goal_Visibility {
	if x != nil {
		return x.Visibility
	}
	return Goal_VISIBILITY_UNSPECIFIED
}

func (x *Goal) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Goal) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Goal) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// BingoCard is a 2D grid representation of multiple Goals for a specific calendar month.
type BingoCard struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Grid       []*BingoCard_GridRow   `protobuf:"bytes,2,rep,name=grid,proto3" json:"grid,omitempty"`
	Year       int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month      int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Goal.create_time is the timestamp when the goal was created.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard) Reset() {
	*x = BingoCard{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard) ProtoMessage() {}

func (x *BingoCard) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard.ProtoReflect.Descriptor instead.
func (*BingoCard) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *BingoCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BingoCard) GetGrid() []*BingoCard_GridRow {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *BingoCard) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BingoCard) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *BingoCard) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *BingoCard) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// CreateBingoCardRequest contains parameters for creating a new bingo card.
type CreateBingoCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent is the user resource name (e.g., "users/123").
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// bingo_card contains the initial state (year, month).
	BingoCard     *BingoCard `protobuf:"bytes,2,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBingoCardRequest) Reset() {
	*x = CreateBingoCardRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBingoCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBingoCardRequest) ProtoMessage() {}

func (x *CreateBingoCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBingoCardRequest.ProtoReflect.Descriptor instead.
func (*CreateBingoCardRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBingoCardRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateBingoCardRequest) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

// CreateBingoCardResponse contains the created BingoCard.
type CreateBingoCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BingoCard     *BingoCard             `protobuf:"bytes,1,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBingoCardResponse) Reset() {
	*x = CreateBingoCardResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBingoCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBingoCardResponse) ProtoMessage() {}

func (x *CreateBingoCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBingoCardResponse.ProtoReflect.Descriptor instead.
func (*CreateBingoCardResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBingoCardResponse) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

// GetBingoCardRequest contains parameters for retrieving a bingo card.
type GetBingoCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GetBingoCardRequest.name is the resource name of the bingo card.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// GetBingoCardRequest.view is the detail level of the returned BingoCard.
	View          GetBingoCardRequest_BingoCardView `protobuf:"varint,2,opt,name=view,proto3,enum=totle_tasks.v1.GetBingoCardRequest_BingoCardView" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBingoCardRequest) Reset() {
	*x = GetBingoCardRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBingoCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBingoCardRequest) ProtoMessage() {}

func (x *GetBingoCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBingoCardRequest.ProtoReflect.Descriptor instead.
func (*GetBingoCardRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *GetBingoCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBingoCardRequest) GetView() GetBingoCardRequest_BingoCardView {
	if x != nil {
		return x.View
	}
	return GetBingoCardRequest_BINGO_CARD_VIEW_UNSPECIFIED
}

// GetBingoCardResponse wraps the retrieved BingoCard resource.
type GetBingoCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BingoCard     *BingoCard             `protobuf:"bytes,1,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBingoCardResponse) Reset() {
	*x = GetBingoCardResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBingoCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBingoCardResponse) ProtoMessage() {}

func (x *GetBingoCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBingoCardResponse.ProtoReflect.Descriptor instead.
func (*GetBingoCardResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *GetBingoCardResponse) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

// UpdateBingoCardRequest contains parameters for modifying a bingo card layout.
type UpdateBingoCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UpdateBingoCardRequest.bingo_card is the bingo card state to update.
	BingoCard *BingoCard `protobuf:"bytes,1,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	// UpdateBingoCardRequest.update_mask is the list of fields to be updated.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBingoCardRequest) Reset() {
	*x = UpdateBingoCardRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBingoCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBingoCardRequest) ProtoMessage() {}

func (x *UpdateBingoCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBingoCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBingoCardRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBingoCardRequest) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

func (x *UpdateBingoCardRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateBingoCardResponse returns the updated BingoCard.
type UpdateBingoCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BingoCard     *BingoCard             `protobuf:"bytes,1,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBingoCardResponse) Reset() {
	*x = UpdateBingoCardResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBingoCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBingoCardResponse) ProtoMessage() {}

func (x *UpdateBingoCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBingoCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBingoCardResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBingoCardResponse) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

// CreateGoalRequest contains parameters for creating a new goal.
type CreateGoalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CreateGoalRequest.parent is the parent resource (e.g., "users/123").
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// CreateGoalRequest.goal is the Goal content to create.
	Goal *Goal `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`
	// CreateGoalRequest.goal_id is an optional client-generated ID for the goal.
	GoalId        string `protobuf:"bytes,3,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoalRequest) Reset() {
	*x = CreateGoalRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoalRequest) ProtoMessage() {}

func (x *CreateGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoalRequest.ProtoReflect.Descriptor instead.
func (*CreateGoalRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGoalRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateGoalRequest) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

func (x *CreateGoalRequest) GetGoalId() string {
	if x != nil {
		return x.GoalId
	}
	return ""
}

// CreateGoalResponse contains the created Goal.
type CreateGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          *Goal                  `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoalResponse) Reset() {
	*x = CreateGoalResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoalResponse) ProtoMessage() {}

func (x *CreateGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoalResponse.ProtoReflect.Descriptor instead.
func (*CreateGoalResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGoalResponse) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

// GetGoalRequest contains parameters for fetching a single goal by name.
type GetGoalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GetGoalRequest.name is the resource name of the goal to retrieve.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalRequest) Reset() {
	*x = GetGoalRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalRequest) ProtoMessage() {}

func (x *GetGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalRequest.ProtoReflect.Descriptor instead.
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *GetGoalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetGoalResponse wraps the retrieved Goal resource.
type GetGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          *Goal                  `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalResponse) Reset() {
	*x = GetGoalResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalResponse) ProtoMessage() {}

func (x *GetGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalResponse.ProtoReflect.Descriptor instead.
func (*GetGoalResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *GetGoalResponse) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

// ListGoalsRequest contains parameters for listing and filtering goals.
type ListGoalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ListGoalsRequest.parent is the parent resource to list goals from.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// ListGoalsRequest.page_size is the max number of goals to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// ListGoalsRequest.page_token is the token for the next set of results.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// ListGoalsRequest.filter is the filter string to narrow down results.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoalsRequest) Reset() {
	*x = ListGoalsRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsRequest) ProtoMessage() {}

func (x *ListGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsRequest.ProtoReflect.Descriptor instead.
func (*ListGoalsRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *ListGoalsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListGoalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGoalsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGoalsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ListGoalsResponse returns a list of goals and pagination metadata.
type ListGoalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoalsResponse) Reset() {
	*x = ListGoalsResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoalsResponse) ProtoMessage() {}

func (x *ListGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoalsResponse.ProtoReflect.Descriptor instead.
func (*ListGoalsResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{13}
}

func (x *ListGoalsResponse) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *ListGoalsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateGoalRequest contains parameters for modifying an existing goal.
type UpdateGoalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UpdateGoalRequest.goal is the goal resource state to update.
	Goal *Goal `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	// UpdateGoalRequest.update_mask is the list of fields to be updated.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoalRequest) Reset() {
	*x = UpdateGoalRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoalRequest) ProtoMessage() {}

func (x *UpdateGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoalRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoalRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateGoalRequest) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

func (x *UpdateGoalRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateGoalResponse returns the updated Goal.
type UpdateGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          *Goal                  `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoalResponse) Reset() {
	*x = UpdateGoalResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoalResponse) ProtoMessage() {}

func (x *UpdateGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoalResponse.ProtoReflect.Descriptor instead.
func (*UpdateGoalResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateGoalResponse) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

// DeleteGoalRequest contains parameters for deleting a goal.
type DeleteGoalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeleteGoalRequest.name is the resource name of the goal to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoalRequest) Reset() {
	*x = DeleteGoalRequest{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoalRequest) ProtoMessage() {}

func (x *DeleteGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoalRequest.ProtoReflect.Descriptor instead.
func (*DeleteGoalRequest) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteGoalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteGoalResponse is an empty response for successful deletion.
type DeleteGoalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoalResponse) Reset() {
	*x = DeleteGoalResponse{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoalResponse) ProtoMessage() {}

func (x *DeleteGoalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoalResponse.ProtoReflect.Descriptor instead.
func (*DeleteGoalResponse) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{17}
}

type BingoCard_Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	GoalValue     *Goal                  `protobuf:"bytes,2,opt,name=goal_value,json=goalValue,proto3" json:"goal_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard_Slot) Reset() {
	*x = BingoCard_Slot{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard_Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard_Slot) ProtoMessage() {}

func (x *BingoCard_Slot) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard_Slot.ProtoReflect.Descriptor instead.
func (*BingoCard_Slot) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BingoCard_Slot) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *BingoCard_Slot) GetGoalValue() *Goal {
	if x != nil {
		return x.GoalValue
	}
	return nil
}

type BingoCard_GridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*BingoCard_Slot      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard_GridRow) Reset() {
	*x = BingoCard_GridRow{}
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard_GridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard_GridRow) ProtoMessage() {}

func (x *BingoCard_GridRow) ProtoReflect() protoreflect.Message {
	mi := &file_totle_tasks_v1_totle_tasks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard_GridRow.ProtoReflect.Descriptor instead.
func (*BingoCard_GridRow) Descriptor() ([]byte, []int) {
	return file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BingoCard_GridRow) GetSlots() []*BingoCard_Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_totle_tasks_v1_totle_tasks_proto protoreflect.FileDescriptor

const file_totle_tasks_v1_totle_tasks_proto_rawDesc = "" +
	"\n" +
	" totle_tasks/v1/totle_tasks.proto\x12\x0etotle_tasks.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x04\n" +
	"\x04Goal\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12$\n" +
	"\vis_assigned\x18\x04 \x01(\bB\x03\xe0A\x03R\n" +
	"isAssigned\x12?\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x1f.totle_tasks.v1.Goal.VisibilityR\n" +
	"visibility\x12$\n" +
	"\vis_archived\x18\x06 \x01(\bB\x03\xe0A\x03R\n" +
	"isArchived\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\"o\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x01\x12\x16\n" +
	"\x12VISIBILITY_FRIENDS\x10\x02\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x03:1\xeaA.\n" +
	"\x1etotletasks.googleapis.com/Goal\x12\fgoals/{goal}\"\xd4\x03\n" +
	"\tBingoCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x04grid\x18\x02 \x03(\v2!.totle_tasks.v1.BingoCard.GridRowR\x04grid\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x04 \x01(\x05R\x05month\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x1aO\n" +
	"\x04Slot\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x123\n" +
	"\n" +
	"goal_value\x18\x02 \x01(\v2\x14.totle_tasks.v1.GoalR\tgoalValue\x1a?\n" +
	"\aGridRow\x124\n" +
	"\x05slots\x18\x01 \x03(\v2\x1e.totle_tasks.v1.BingoCard.SlotR\x05slots:A\xeaA>\n" +
	"#totletasks.googleapis.com/BingoCard\x12\x17bingoCards/{bingo_card}\"t\n" +
	"\x16CreateBingoCardRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12=\n" +
	"\n" +
	"bingo_card\x18\x02 \x01(\v2\x19.totle_tasks.v1.BingoCardB\x03\xe0A\x02R\tbingoCard\"S\n" +
	"\x17CreateBingoCardResponse\x128\n" +
	"\n" +
	"bingo_card\x18\x01 \x01(\v2\x19.totle_tasks.v1.BingoCardR\tbingoCard\"\xdc\x01\n" +
	"\x13GetBingoCardRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12E\n" +
	"\x04view\x18\x02 \x01(\x0e21.totle_tasks.v1.GetBingoCardRequest.BingoCardViewR\x04view\"e\n" +
	"\rBingoCardView\x12\x1f\n" +
	"\x1bBINGO_CARD_VIEW_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BINGO_CARD_VIEW_BASIC\x10\x01\x12\x18\n" +
	"\x14BINGO_CARD_VIEW_FULL\x10\x02\"P\n" +
	"\x14GetBingoCardResponse\x128\n" +
	"\n" +
	"bingo_card\x18\x01 \x01(\v2\x19.totle_tasks.v1.BingoCardR\tbingoCard\"\x94\x01\n" +
	"\x16UpdateBingoCardRequest\x12=\n" +
	"\n" +
	"bingo_card\x18\x01 \x01(\v2\x19.totle_tasks.v1.BingoCardB\x03\xe0A\x02R\tbingoCard\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"S\n" +
	"\x17UpdateBingoCardResponse\x128\n" +
	"\n" +
	"bingo_card\x18\x01 \x01(\v2\x19.totle_tasks.v1.BingoCardR\tbingoCard\"x\n" +
	"\x11CreateGoalRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12-\n" +
	"\x04goal\x18\x02 \x01(\v2\x14.totle_tasks.v1.GoalB\x03\xe0A\x02R\x04goal\x12\x17\n" +
	"\agoal_id\x18\x03 \x01(\tR\x06goalId\">\n" +
	"\x12CreateGoalResponse\x12(\n" +
	"\x04goal\x18\x01 \x01(\v2\x14.totle_tasks.v1.GoalR\x04goal\"L\n" +
	"\x0eGetGoalRequest\x12:\n" +
	"\x04name\x18\x01 \x01(\tB&\xe0A\x02\xfaA \n" +
	"\x1etotletasks.googleapis.com/GoalR\x04name\";\n" +
	"\x0fGetGoalResponse\x12(\n" +
	"\x04goal\x18\x01 \x01(\v2\x14.totle_tasks.v1.GoalR\x04goal\"\x83\x01\n" +
	"\x10ListGoalsRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"g\n" +
	"\x11ListGoalsResponse\x12*\n" +
	"\x05goals\x18\x01 \x03(\v2\x14.totle_tasks.v1.GoalR\x05goals\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x7f\n" +
	"\x11UpdateGoalRequest\x12-\n" +
	"\x04goal\x18\x01 \x01(\v2\x14.totle_tasks.v1.GoalB\x03\xe0A\x02R\x04goal\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\">\n" +
	"\x12UpdateGoalResponse\x12(\n" +
	"\x04goal\x18\x01 \x01(\v2\x14.totle_tasks.v1.GoalR\x04goal\",\n" +
	"\x11DeleteGoalRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x14\n" +
	"\x12DeleteGoalResponse2\xaa\x03\n" +
	"\vGoalService\x12S\n" +
	"\n" +
	"CreateGoal\x12!.totle_tasks.v1.CreateGoalRequest\x1a\".totle_tasks.v1.CreateGoalResponse\x12J\n" +
	"\aGetGoal\x12\x1e.totle_tasks.v1.GetGoalRequest\x1a\x1f.totle_tasks.v1.GetGoalResponse\x12P\n" +
	"\tListGoals\x12 .totle_tasks.v1.ListGoalsRequest\x1a!.totle_tasks.v1.ListGoalsResponse\x12S\n" +
	"\n" +
	"UpdateGoal\x12!.totle_tasks.v1.UpdateGoalRequest\x1a\".totle_tasks.v1.UpdateGoalResponse\x12S\n" +
	"\n" +
	"DeleteGoal\x12!.totle_tasks.v1.DeleteGoalRequest\x1a\".totle_tasks.v1.DeleteGoalResponse2\xb1\x02\n" +
	"\fBingoService\x12b\n" +
	"\x0fCreateBingoCard\x12&.totle_tasks.v1.CreateBingoCardRequest\x1a'.totle_tasks.v1.CreateBingoCardResponse\x12Y\n" +
	"\fGetBingoCard\x12#.totle_tasks.v1.GetBingoCardRequest\x1a$.totle_tasks.v1.GetBingoCardResponse\x12b\n" +
	"\x0fUpdateBingoCard\x12&.totle_tasks.v1.UpdateBingoCardRequest\x1a'.totle_tasks.v1.UpdateBingoCardResponseBGZEgithub.com/bibyen/totle-tasks/internal/pb/totle_tasks/v1;totletasksv1b\x06proto3"

var (
	file_totle_tasks_v1_totle_tasks_proto_rawDescOnce sync.Once
	file_totle_tasks_v1_totle_tasks_proto_rawDescData []byte
)

func file_totle_tasks_v1_totle_tasks_proto_rawDescGZIP() []byte {
	file_totle_tasks_v1_totle_tasks_proto_rawDescOnce.Do(func() {
		file_totle_tasks_v1_totle_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_totle_tasks_v1_totle_tasks_proto_rawDesc), len(file_totle_tasks_v1_totle_tasks_proto_rawDesc)))
	})
	return file_totle_tasks_v1_totle_tasks_proto_rawDescData
}

var file_totle_tasks_v1_totle_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_totle_tasks_v1_totle_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_totle_tasks_v1_totle_tasks_proto_goTypes = []any{
	(Goal_Visibility)(0),                   // 0: totle_tasks.v1.Goal.Visibility
	(GetBingoCardRequest_BingoCardView)(0), // 1: totle_tasks.v1.GetBingoCardRequest.BingoCardView
	(*Goal)(nil),                           // 2: totle_tasks.v1.Goal
	(*BingoCard)(nil),                      // 3: totle_tasks.v1.BingoCard
	(*CreateBingoCardRequest)(nil),         // 4: totle_tasks.v1.CreateBingoCardRequest
	(*CreateBingoCardResponse)(nil),        // 5: totle_tasks.v1.CreateBingoCardResponse
	(*GetBingoCardRequest)(nil),            // 6: totle_tasks.v1.GetBingoCardRequest
	(*GetBingoCardResponse)(nil),           // 7: totle_tasks.v1.GetBingoCardResponse
	(*UpdateBingoCardRequest)(nil),         // 8: totle_tasks.v1.UpdateBingoCardRequest
	(*UpdateBingoCardResponse)(nil),        // 9: totle_tasks.v1.UpdateBingoCardResponse
	(*CreateGoalRequest)(nil),              // 10: totle_tasks.v1.CreateGoalRequest
	(*CreateGoalResponse)(nil),             // 11: totle_tasks.v1.CreateGoalResponse
	(*GetGoalRequest)(nil),                 // 12: totle_tasks.v1.GetGoalRequest
	(*GetGoalResponse)(nil),                // 13: totle_tasks.v1.GetGoalResponse
	(*ListGoalsRequest)(nil),               // 14: totle_tasks.v1.ListGoalsRequest
	(*ListGoalsResponse)(nil),              // 15: totle_tasks.v1.ListGoalsResponse
	(*UpdateGoalRequest)(nil),              // 16: totle_tasks.v1.UpdateGoalRequest
	(*UpdateGoalResponse)(nil),             // 17: totle_tasks.v1.UpdateGoalResponse
	(*DeleteGoalRequest)(nil),              // 18: totle_tasks.v1.DeleteGoalRequest
	(*DeleteGoalResponse)(nil),             // 19: totle_tasks.v1.DeleteGoalResponse
	(*BingoCard_Slot)(nil),                 // 20: totle_tasks.v1.BingoCard.Slot
	(*BingoCard_GridRow)(nil),              // 21: totle_tasks.v1.BingoCard.GridRow
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 23: google.protobuf.FieldMask
}
var file_totle_tasks_v1_totle_tasks_proto_depIdxs = []int32{
	0,  // 0: totle_tasks.v1.Goal.visibility:type_name -> totle_tasks.v1.Goal.Visibility
	22, // 1: totle_tasks.v1.Goal.create_time:type_name -> google.protobuf.Timestamp
	22, // 2: totle_tasks.v1.Goal.update_time:type_name -> google.protobuf.Timestamp
	21, // 3: totle_tasks.v1.BingoCard.grid:type_name -> totle_tasks.v1.BingoCard.GridRow
	22, // 4: totle_tasks.v1.BingoCard.update_time:type_name -> google.protobuf.Timestamp
	22, // 5: totle_tasks.v1.BingoCard.create_time:type_name -> google.protobuf.Timestamp
	3,  // 6: totle_tasks.v1.CreateBingoCardRequest.bingo_card:type_name -> totle_tasks.v1.BingoCard
	3,  // 7: totle_tasks.v1.CreateBingoCardResponse.bingo_card:type_name -> totle_tasks.v1.BingoCard
	1,  // 8: totle_tasks.v1.GetBingoCardRequest.view:type_name -> totle_tasks.v1.GetBingoCardRequest.BingoCardView
	3,  // 9: totle_tasks.v1.GetBingoCardResponse.bingo_card:type_name -> totle_tasks.v1.BingoCard
	3,  // 10: totle_tasks.v1.UpdateBingoCardRequest.bingo_card:type_name -> totle_tasks.v1.BingoCard
	23, // 11: totle_tasks.v1.UpdateBingoCardRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 12: totle_tasks.v1.UpdateBingoCardResponse.bingo_card:type_name -> totle_tasks.v1.BingoCard
	2,  // 13: totle_tasks.v1.CreateGoalRequest.goal:type_name -> totle_tasks.v1.Goal
	2,  // 14: totle_tasks.v1.CreateGoalResponse.goal:type_name -> totle_tasks.v1.Goal
	2,  // 15: totle_tasks.v1.GetGoalResponse.goal:type_name -> totle_tasks.v1.Goal
	2,  // 16: totle_tasks.v1.ListGoalsResponse.goals:type_name -> totle_tasks.v1.Goal
	2,  // 17: totle_tasks.v1.UpdateGoalRequest.goal:type_name -> totle_tasks.v1.Goal
	23, // 18: totle_tasks.v1.UpdateGoalRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 19: totle_tasks.v1.UpdateGoalResponse.goal:type_name -> totle_tasks.v1.Goal
	2,  // 20: totle_tasks.v1.BingoCard.Slot.goal_value:type_name -> totle_tasks.v1.Goal
	20, // 21: totle_tasks.v1.BingoCard.GridRow.slots:type_name -> totle_tasks.v1.BingoCard.Slot
	10, // 22: totle_tasks.v1.GoalService.CreateGoal:input_type -> totle_tasks.v1.CreateGoalRequest
	12, // 23: totle_tasks.v1.GoalService.GetGoal:input_type -> totle_tasks.v1.GetGoalRequest
	14, // 24: totle_tasks.v1.GoalService.ListGoals:input_type -> totle_tasks.v1.ListGoalsRequest
	16, // 25: totle_tasks.v1.GoalService.UpdateGoal:input_type -> totle_tasks.v1.UpdateGoalRequest
	18, // 26: totle_tasks.v1.GoalService.DeleteGoal:input_type -> totle_tasks.v1.DeleteGoalRequest
	4,  // 27: totle_tasks.v1.BingoService.CreateBingoCard:input_type -> totle_tasks.v1.CreateBingoCardRequest
	6,  // 28: totle_tasks.v1.BingoService.GetBingoCard:input_type -> totle_tasks.v1.GetBingoCardRequest
	8,  // 29: totle_tasks.v1.BingoService.UpdateBingoCard:input_type -> totle_tasks.v1.UpdateBingoCardRequest
	11, // 30: totle_tasks.v1.GoalService.CreateGoal:output_type -> totle_tasks.v1.CreateGoalResponse
	13, // 31: totle_tasks.v1.GoalService.GetGoal:output_type -> totle_tasks.v1.GetGoalResponse
	15, // 32: totle_tasks.v1.GoalService.ListGoals:output_type -> totle_tasks.v1.ListGoalsResponse
	17, // 33: totle_tasks.v1.GoalService.UpdateGoal:output_type -> totle_tasks.v1.UpdateGoalResponse
	19, // 34: totle_tasks.v1.GoalService.DeleteGoal:output_type -> totle_tasks.v1.DeleteGoalResponse
	5,  // 35: totle_tasks.v1.BingoService.CreateBingoCard:output_type -> totle_tasks.v1.CreateBingoCardResponse
	7,  // 36: totle_tasks.v1.BingoService.GetBingoCard:output_type -> totle_tasks.v1.GetBingoCardResponse
	9,  // 37: totle_tasks.v1.BingoService.UpdateBingoCard:output_type -> totle_tasks.v1.UpdateBingoCardResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_totle_tasks_v1_totle_tasks_proto_init() }
func file_totle_tasks_v1_totle_tasks_proto_init() {
	if File_totle_tasks_v1_totle_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_totle_tasks_v1_totle_tasks_proto_rawDesc), len(file_totle_tasks_v1_totle_tasks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_totle_tasks_v1_totle_tasks_proto_goTypes,
		DependencyIndexes: file_totle_tasks_v1_totle_tasks_proto_depIdxs,
		EnumInfos:         file_totle_tasks_v1_totle_tasks_proto_enumTypes,
		MessageInfos:      file_totle_tasks_v1_totle_tasks_proto_msgTypes,
	}.Build()
	File_totle_tasks_v1_totle_tasks_proto = out.File
	file_totle_tasks_v1_totle_tasks_proto_goTypes = nil
	file_totle_tasks_v1_totle_tasks_proto_depIdxs = nil
}
