// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: totle_tasks/v1/totle_tasks.proto

package totletasksv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bibyen/totle-tasks/internal/pb/totle_tasks/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GoalServiceName is the fully-qualified name of the GoalService service.
	GoalServiceName = "totle_tasks.v1.GoalService"
	// BingoServiceName is the fully-qualified name of the BingoService service.
	BingoServiceName = "totle_tasks.v1.BingoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GoalServiceCreateGoalProcedure is the fully-qualified name of the GoalService's CreateGoal RPC.
	GoalServiceCreateGoalProcedure = "/totle_tasks.v1.GoalService/CreateGoal"
	// GoalServiceGetGoalProcedure is the fully-qualified name of the GoalService's GetGoal RPC.
	GoalServiceGetGoalProcedure = "/totle_tasks.v1.GoalService/GetGoal"
	// GoalServiceListGoalsProcedure is the fully-qualified name of the GoalService's ListGoals RPC.
	GoalServiceListGoalsProcedure = "/totle_tasks.v1.GoalService/ListGoals"
	// GoalServiceUpdateGoalProcedure is the fully-qualified name of the GoalService's UpdateGoal RPC.
	GoalServiceUpdateGoalProcedure = "/totle_tasks.v1.GoalService/UpdateGoal"
	// GoalServiceDeleteGoalProcedure is the fully-qualified name of the GoalService's DeleteGoal RPC.
	GoalServiceDeleteGoalProcedure = "/totle_tasks.v1.GoalService/DeleteGoal"
	// BingoServiceGetBingoCardProcedure is the fully-qualified name of the BingoService's GetBingoCard
	// RPC.
	BingoServiceGetBingoCardProcedure = "/totle_tasks.v1.BingoService/GetBingoCard"
	// BingoServiceUpdateBingoCardProcedure is the fully-qualified name of the BingoService's
	// UpdateBingoCard RPC.
	BingoServiceUpdateBingoCardProcedure = "/totle_tasks.v1.BingoService/UpdateBingoCard"
)

// GoalServiceClient is a client for the totle_tasks.v1.GoalService service.
type GoalServiceClient interface {
	// GoalService.CreateGoal creates a new Goal for the authenticated user.
	CreateGoal(context.Context, *connect.Request[v1.CreateGoalRequest]) (*connect.Response[v1.CreateGoalResponse], error)
	// GoalService.GetGoal retrieves a specific Goal by its unique resource name.
	GetGoal(context.Context, *connect.Request[v1.GetGoalRequest]) (*connect.Response[v1.GetGoalResponse], error)
	// GoalService.ListGoals returns a paginated list of Goals belonging to the parent resource.
	ListGoals(context.Context, *connect.Request[v1.ListGoalsRequest]) (*connect.Response[v1.ListGoalsResponse], error)
	// GoalService.UpdateGoal updates specific fields of an existing Goal using a FieldMask.
	UpdateGoal(context.Context, *connect.Request[v1.UpdateGoalRequest]) (*connect.Response[v1.UpdateGoalResponse], error)
	// GoalService.DeleteGoal permanently removes a Goal from the system.
	DeleteGoal(context.Context, *connect.Request[v1.DeleteGoalRequest]) (*connect.Response[v1.DeleteGoalResponse], error)
}

// NewGoalServiceClient constructs a client for the totle_tasks.v1.GoalService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGoalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GoalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	goalServiceMethods := v1.File_totle_tasks_v1_totle_tasks_proto.Services().ByName("GoalService").Methods()
	return &goalServiceClient{
		createGoal: connect.NewClient[v1.CreateGoalRequest, v1.CreateGoalResponse](
			httpClient,
			baseURL+GoalServiceCreateGoalProcedure,
			connect.WithSchema(goalServiceMethods.ByName("CreateGoal")),
			connect.WithClientOptions(opts...),
		),
		getGoal: connect.NewClient[v1.GetGoalRequest, v1.GetGoalResponse](
			httpClient,
			baseURL+GoalServiceGetGoalProcedure,
			connect.WithSchema(goalServiceMethods.ByName("GetGoal")),
			connect.WithClientOptions(opts...),
		),
		listGoals: connect.NewClient[v1.ListGoalsRequest, v1.ListGoalsResponse](
			httpClient,
			baseURL+GoalServiceListGoalsProcedure,
			connect.WithSchema(goalServiceMethods.ByName("ListGoals")),
			connect.WithClientOptions(opts...),
		),
		updateGoal: connect.NewClient[v1.UpdateGoalRequest, v1.UpdateGoalResponse](
			httpClient,
			baseURL+GoalServiceUpdateGoalProcedure,
			connect.WithSchema(goalServiceMethods.ByName("UpdateGoal")),
			connect.WithClientOptions(opts...),
		),
		deleteGoal: connect.NewClient[v1.DeleteGoalRequest, v1.DeleteGoalResponse](
			httpClient,
			baseURL+GoalServiceDeleteGoalProcedure,
			connect.WithSchema(goalServiceMethods.ByName("DeleteGoal")),
			connect.WithClientOptions(opts...),
		),
	}
}

// goalServiceClient implements GoalServiceClient.
type goalServiceClient struct {
	createGoal *connect.Client[v1.CreateGoalRequest, v1.CreateGoalResponse]
	getGoal    *connect.Client[v1.GetGoalRequest, v1.GetGoalResponse]
	listGoals  *connect.Client[v1.ListGoalsRequest, v1.ListGoalsResponse]
	updateGoal *connect.Client[v1.UpdateGoalRequest, v1.UpdateGoalResponse]
	deleteGoal *connect.Client[v1.DeleteGoalRequest, v1.DeleteGoalResponse]
}

// CreateGoal calls totle_tasks.v1.GoalService.CreateGoal.
func (c *goalServiceClient) CreateGoal(ctx context.Context, req *connect.Request[v1.CreateGoalRequest]) (*connect.Response[v1.CreateGoalResponse], error) {
	return c.createGoal.CallUnary(ctx, req)
}

// GetGoal calls totle_tasks.v1.GoalService.GetGoal.
func (c *goalServiceClient) GetGoal(ctx context.Context, req *connect.Request[v1.GetGoalRequest]) (*connect.Response[v1.GetGoalResponse], error) {
	return c.getGoal.CallUnary(ctx, req)
}

// ListGoals calls totle_tasks.v1.GoalService.ListGoals.
func (c *goalServiceClient) ListGoals(ctx context.Context, req *connect.Request[v1.ListGoalsRequest]) (*connect.Response[v1.ListGoalsResponse], error) {
	return c.listGoals.CallUnary(ctx, req)
}

// UpdateGoal calls totle_tasks.v1.GoalService.UpdateGoal.
func (c *goalServiceClient) UpdateGoal(ctx context.Context, req *connect.Request[v1.UpdateGoalRequest]) (*connect.Response[v1.UpdateGoalResponse], error) {
	return c.updateGoal.CallUnary(ctx, req)
}

// DeleteGoal calls totle_tasks.v1.GoalService.DeleteGoal.
func (c *goalServiceClient) DeleteGoal(ctx context.Context, req *connect.Request[v1.DeleteGoalRequest]) (*connect.Response[v1.DeleteGoalResponse], error) {
	return c.deleteGoal.CallUnary(ctx, req)
}

// GoalServiceHandler is an implementation of the totle_tasks.v1.GoalService service.
type GoalServiceHandler interface {
	// GoalService.CreateGoal creates a new Goal for the authenticated user.
	CreateGoal(context.Context, *connect.Request[v1.CreateGoalRequest]) (*connect.Response[v1.CreateGoalResponse], error)
	// GoalService.GetGoal retrieves a specific Goal by its unique resource name.
	GetGoal(context.Context, *connect.Request[v1.GetGoalRequest]) (*connect.Response[v1.GetGoalResponse], error)
	// GoalService.ListGoals returns a paginated list of Goals belonging to the parent resource.
	ListGoals(context.Context, *connect.Request[v1.ListGoalsRequest]) (*connect.Response[v1.ListGoalsResponse], error)
	// GoalService.UpdateGoal updates specific fields of an existing Goal using a FieldMask.
	UpdateGoal(context.Context, *connect.Request[v1.UpdateGoalRequest]) (*connect.Response[v1.UpdateGoalResponse], error)
	// GoalService.DeleteGoal permanently removes a Goal from the system.
	DeleteGoal(context.Context, *connect.Request[v1.DeleteGoalRequest]) (*connect.Response[v1.DeleteGoalResponse], error)
}

// NewGoalServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGoalServiceHandler(svc GoalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	goalServiceMethods := v1.File_totle_tasks_v1_totle_tasks_proto.Services().ByName("GoalService").Methods()
	goalServiceCreateGoalHandler := connect.NewUnaryHandler(
		GoalServiceCreateGoalProcedure,
		svc.CreateGoal,
		connect.WithSchema(goalServiceMethods.ByName("CreateGoal")),
		connect.WithHandlerOptions(opts...),
	)
	goalServiceGetGoalHandler := connect.NewUnaryHandler(
		GoalServiceGetGoalProcedure,
		svc.GetGoal,
		connect.WithSchema(goalServiceMethods.ByName("GetGoal")),
		connect.WithHandlerOptions(opts...),
	)
	goalServiceListGoalsHandler := connect.NewUnaryHandler(
		GoalServiceListGoalsProcedure,
		svc.ListGoals,
		connect.WithSchema(goalServiceMethods.ByName("ListGoals")),
		connect.WithHandlerOptions(opts...),
	)
	goalServiceUpdateGoalHandler := connect.NewUnaryHandler(
		GoalServiceUpdateGoalProcedure,
		svc.UpdateGoal,
		connect.WithSchema(goalServiceMethods.ByName("UpdateGoal")),
		connect.WithHandlerOptions(opts...),
	)
	goalServiceDeleteGoalHandler := connect.NewUnaryHandler(
		GoalServiceDeleteGoalProcedure,
		svc.DeleteGoal,
		connect.WithSchema(goalServiceMethods.ByName("DeleteGoal")),
		connect.WithHandlerOptions(opts...),
	)
	return "/totle_tasks.v1.GoalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GoalServiceCreateGoalProcedure:
			goalServiceCreateGoalHandler.ServeHTTP(w, r)
		case GoalServiceGetGoalProcedure:
			goalServiceGetGoalHandler.ServeHTTP(w, r)
		case GoalServiceListGoalsProcedure:
			goalServiceListGoalsHandler.ServeHTTP(w, r)
		case GoalServiceUpdateGoalProcedure:
			goalServiceUpdateGoalHandler.ServeHTTP(w, r)
		case GoalServiceDeleteGoalProcedure:
			goalServiceDeleteGoalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGoalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGoalServiceHandler struct{}

func (UnimplementedGoalServiceHandler) CreateGoal(context.Context, *connect.Request[v1.CreateGoalRequest]) (*connect.Response[v1.CreateGoalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.GoalService.CreateGoal is not implemented"))
}

func (UnimplementedGoalServiceHandler) GetGoal(context.Context, *connect.Request[v1.GetGoalRequest]) (*connect.Response[v1.GetGoalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.GoalService.GetGoal is not implemented"))
}

func (UnimplementedGoalServiceHandler) ListGoals(context.Context, *connect.Request[v1.ListGoalsRequest]) (*connect.Response[v1.ListGoalsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.GoalService.ListGoals is not implemented"))
}

func (UnimplementedGoalServiceHandler) UpdateGoal(context.Context, *connect.Request[v1.UpdateGoalRequest]) (*connect.Response[v1.UpdateGoalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.GoalService.UpdateGoal is not implemented"))
}

func (UnimplementedGoalServiceHandler) DeleteGoal(context.Context, *connect.Request[v1.DeleteGoalRequest]) (*connect.Response[v1.DeleteGoalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.GoalService.DeleteGoal is not implemented"))
}

// BingoServiceClient is a client for the totle_tasks.v1.BingoService service.
type BingoServiceClient interface {
	// BingoService.GetBingoCard retrieves the bingo card for a specific year and month.
	GetBingoCard(context.Context, *connect.Request[v1.GetBingoCardRequest]) (*connect.Response[v1.GetBingoCardResponse], error)
	// BingoService.UpdateBingoCard updates the layout or goal assignments within a bingo card.
	UpdateBingoCard(context.Context, *connect.Request[v1.UpdateBingoCardRequest]) (*connect.Response[v1.UpdateBingoCardResponse], error)
}

// NewBingoServiceClient constructs a client for the totle_tasks.v1.BingoService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBingoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BingoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bingoServiceMethods := v1.File_totle_tasks_v1_totle_tasks_proto.Services().ByName("BingoService").Methods()
	return &bingoServiceClient{
		getBingoCard: connect.NewClient[v1.GetBingoCardRequest, v1.GetBingoCardResponse](
			httpClient,
			baseURL+BingoServiceGetBingoCardProcedure,
			connect.WithSchema(bingoServiceMethods.ByName("GetBingoCard")),
			connect.WithClientOptions(opts...),
		),
		updateBingoCard: connect.NewClient[v1.UpdateBingoCardRequest, v1.UpdateBingoCardResponse](
			httpClient,
			baseURL+BingoServiceUpdateBingoCardProcedure,
			connect.WithSchema(bingoServiceMethods.ByName("UpdateBingoCard")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bingoServiceClient implements BingoServiceClient.
type bingoServiceClient struct {
	getBingoCard    *connect.Client[v1.GetBingoCardRequest, v1.GetBingoCardResponse]
	updateBingoCard *connect.Client[v1.UpdateBingoCardRequest, v1.UpdateBingoCardResponse]
}

// GetBingoCard calls totle_tasks.v1.BingoService.GetBingoCard.
func (c *bingoServiceClient) GetBingoCard(ctx context.Context, req *connect.Request[v1.GetBingoCardRequest]) (*connect.Response[v1.GetBingoCardResponse], error) {
	return c.getBingoCard.CallUnary(ctx, req)
}

// UpdateBingoCard calls totle_tasks.v1.BingoService.UpdateBingoCard.
func (c *bingoServiceClient) UpdateBingoCard(ctx context.Context, req *connect.Request[v1.UpdateBingoCardRequest]) (*connect.Response[v1.UpdateBingoCardResponse], error) {
	return c.updateBingoCard.CallUnary(ctx, req)
}

// BingoServiceHandler is an implementation of the totle_tasks.v1.BingoService service.
type BingoServiceHandler interface {
	// BingoService.GetBingoCard retrieves the bingo card for a specific year and month.
	GetBingoCard(context.Context, *connect.Request[v1.GetBingoCardRequest]) (*connect.Response[v1.GetBingoCardResponse], error)
	// BingoService.UpdateBingoCard updates the layout or goal assignments within a bingo card.
	UpdateBingoCard(context.Context, *connect.Request[v1.UpdateBingoCardRequest]) (*connect.Response[v1.UpdateBingoCardResponse], error)
}

// NewBingoServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBingoServiceHandler(svc BingoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bingoServiceMethods := v1.File_totle_tasks_v1_totle_tasks_proto.Services().ByName("BingoService").Methods()
	bingoServiceGetBingoCardHandler := connect.NewUnaryHandler(
		BingoServiceGetBingoCardProcedure,
		svc.GetBingoCard,
		connect.WithSchema(bingoServiceMethods.ByName("GetBingoCard")),
		connect.WithHandlerOptions(opts...),
	)
	bingoServiceUpdateBingoCardHandler := connect.NewUnaryHandler(
		BingoServiceUpdateBingoCardProcedure,
		svc.UpdateBingoCard,
		connect.WithSchema(bingoServiceMethods.ByName("UpdateBingoCard")),
		connect.WithHandlerOptions(opts...),
	)
	return "/totle_tasks.v1.BingoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BingoServiceGetBingoCardProcedure:
			bingoServiceGetBingoCardHandler.ServeHTTP(w, r)
		case BingoServiceUpdateBingoCardProcedure:
			bingoServiceUpdateBingoCardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBingoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBingoServiceHandler struct{}

func (UnimplementedBingoServiceHandler) GetBingoCard(context.Context, *connect.Request[v1.GetBingoCardRequest]) (*connect.Response[v1.GetBingoCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.BingoService.GetBingoCard is not implemented"))
}

func (UnimplementedBingoServiceHandler) UpdateBingoCard(context.Context, *connect.Request[v1.UpdateBingoCardRequest]) (*connect.Response[v1.UpdateBingoCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("totle_tasks.v1.BingoService.UpdateBingoCard is not implemented"))
}
