// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/totle_tasks.proto

package totletasksv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Goal_Visibility int32

const (
	Goal_VISIBILITY_UNSPECIFIED Goal_Visibility = 0
	Goal_PRIVATE                Goal_Visibility = 1
	Goal_PUBLIC                 Goal_Visibility = 2
)

// Enum value maps for Goal_Visibility.
var (
	Goal_Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "PRIVATE",
		2: "PUBLIC",
	}
	Goal_Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"PRIVATE":                1,
		"PUBLIC":                 2,
	}
)

func (x Goal_Visibility) Enum() *Goal_Visibility {
	p := new(Goal_Visibility)
	*p = x
	return p
}

func (x Goal_Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Goal_Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_totle_tasks_proto_enumTypes[0].Descriptor()
}

func (Goal_Visibility) Type() protoreflect.EnumType {
	return &file_v1_totle_tasks_proto_enumTypes[0]
}

func (x Goal_Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Goal_Visibility.Descriptor instead.
func (Goal_Visibility) EnumDescriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{0, 0}
}

type GetBingoCardRequest_View int32

const (
	GetBingoCardRequest_VIEW_UNSPECIFIED GetBingoCardRequest_View = 0
	GetBingoCardRequest_BASIC            GetBingoCardRequest_View = 1 // Returns slot goal_names only.
	GetBingoCardRequest_FULL             GetBingoCardRequest_View = 2 // Hydrates goal_data for all slots.
)

// Enum value maps for GetBingoCardRequest_View.
var (
	GetBingoCardRequest_View_name = map[int32]string{
		0: "VIEW_UNSPECIFIED",
		1: "BASIC",
		2: "FULL",
	}
	GetBingoCardRequest_View_value = map[string]int32{
		"VIEW_UNSPECIFIED": 0,
		"BASIC":            1,
		"FULL":             2,
	}
)

func (x GetBingoCardRequest_View) Enum() *GetBingoCardRequest_View {
	p := new(GetBingoCardRequest_View)
	*p = x
	return p
}

func (x GetBingoCardRequest_View) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetBingoCardRequest_View) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_totle_tasks_proto_enumTypes[1].Descriptor()
}

func (GetBingoCardRequest_View) Type() protoreflect.EnumType {
	return &file_v1_totle_tasks_proto_enumTypes[1]
}

func (x GetBingoCardRequest_View) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetBingoCardRequest_View.Descriptor instead.
func (GetBingoCardRequest_View) EnumDescriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{10, 0}
}

type Goal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Format: users/{user}/goals/{goal_id}
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Output only. True if this goal is placed on a BingoCard.
	// Prevents deletion and exclusion from 'Available' list.
	IsAssigned    bool                   `protobuf:"varint,4,opt,name=is_assigned,json=isAssigned,proto3" json:"is_assigned,omitempty"`
	Visibility    Goal_Visibility        `protobuf:"varint,5,opt,name=visibility,proto3,enum=totle_tasks.v1.Goal_Visibility" json:"visibility,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_v1_totle_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Goal) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Goal) GetIsAssigned() bool {
	if x != nil {
		return x.IsAssigned
	}
	return false
}

func (x *Goal) GetVisibility() Goal_Visibility {
	if x != nil {
		return x.Visibility
	}
	return Goal_VISIBILITY_UNSPECIFIED
}

func (x *Goal) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type BingoCard struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Format: users/{user}/bingoCards/{YYYY-MM}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The 2D grid structure.
	Grid []*BingoCard_GridRow `protobuf:"bytes,2,rep,name=grid,proto3" json:"grid,omitempty"`
	// Immutables lock the card to its specific time bucket.
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard) Reset() {
	*x = BingoCard{}
	mi := &file_v1_totle_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard) ProtoMessage() {}

func (x *BingoCard) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard.ProtoReflect.Descriptor instead.
func (*BingoCard) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *BingoCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BingoCard) GetGrid() []*BingoCard_GridRow {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *BingoCard) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BingoCard) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *BingoCard) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Goal          *Goal                  `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoalRequest) Reset() {
	*x = CreateGoalRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoalRequest) ProtoMessage() {}

func (x *CreateGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoalRequest.ProtoReflect.Descriptor instead.
func (*CreateGoalRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGoalRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateGoalRequest) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

type GetGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoalRequest) Reset() {
	*x = GetGoalRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalRequest) ProtoMessage() {}

func (x *GetGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalRequest.ProtoReflect.Descriptor instead.
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAvailableGoalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent format: users/{user}
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableGoalsRequest) Reset() {
	*x = ListAvailableGoalsRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableGoalsRequest) ProtoMessage() {}

func (x *ListAvailableGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableGoalsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableGoalsRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *ListAvailableGoalsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAvailableGoalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAvailableGoalsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAvailableGoalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableGoalsResponse) Reset() {
	*x = ListAvailableGoalsResponse{}
	mi := &file_v1_totle_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableGoalsResponse) ProtoMessage() {}

func (x *ListAvailableGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableGoalsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableGoalsResponse) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *ListAvailableGoalsResponse) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *ListAvailableGoalsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchGetGoalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent format: users/{user}
	Parent        string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Names         []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGoalsRequest) Reset() {
	*x = BatchGetGoalsRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGoalsRequest) ProtoMessage() {}

func (x *BatchGetGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGoalsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetGoalsRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetGoalsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchGetGoalsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type BatchGetGoalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetGoalsResponse) Reset() {
	*x = BatchGetGoalsResponse{}
	mi := &file_v1_totle_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetGoalsResponse) ProtoMessage() {}

func (x *BatchGetGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetGoalsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetGoalsResponse) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetGoalsResponse) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

type UpdateGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          *Goal                  `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoalRequest) Reset() {
	*x = UpdateGoalRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoalRequest) ProtoMessage() {}

func (x *UpdateGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoalRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoalRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGoalRequest) GetGoal() *Goal {
	if x != nil {
		return x.Goal
	}
	return nil
}

func (x *UpdateGoalRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteGoalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoalRequest) Reset() {
	*x = DeleteGoalRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoalRequest) ProtoMessage() {}

func (x *DeleteGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoalRequest.ProtoReflect.Descriptor instead.
func (*DeleteGoalRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteGoalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBingoCardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{user}/bingoCards/{YYYY-MM}
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	View          GetBingoCardRequest_View `protobuf:"varint,2,opt,name=view,proto3,enum=totle_tasks.v1.GetBingoCardRequest_View" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBingoCardRequest) Reset() {
	*x = GetBingoCardRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBingoCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBingoCardRequest) ProtoMessage() {}

func (x *GetBingoCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBingoCardRequest.ProtoReflect.Descriptor instead.
func (*GetBingoCardRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *GetBingoCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBingoCardRequest) GetView() GetBingoCardRequest_View {
	if x != nil {
		return x.View
	}
	return GetBingoCardRequest_VIEW_UNSPECIFIED
}

type UpdateBingoCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BingoCard     *BingoCard             `protobuf:"bytes,1,opt,name=bingo_card,json=bingoCard,proto3" json:"bingo_card,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBingoCardRequest) Reset() {
	*x = UpdateBingoCardRequest{}
	mi := &file_v1_totle_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBingoCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBingoCardRequest) ProtoMessage() {}

func (x *UpdateBingoCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBingoCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBingoCardRequest) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBingoCardRequest) GetBingoCard() *BingoCard {
	if x != nil {
		return x.BingoCard
	}
	return nil
}

func (x *UpdateBingoCardRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type BingoCard_Slot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the goal.
	GoalName string `protobuf:"bytes,1,opt,name=goal_name,json=goalName,proto3" json:"goal_name,omitempty"`
	// Output only. Populated only if GetBingoCardRequest.view == VIEW_FULL.
	GoalData      *Goal `protobuf:"bytes,2,opt,name=goal_data,json=goalData,proto3" json:"goal_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard_Slot) Reset() {
	*x = BingoCard_Slot{}
	mi := &file_v1_totle_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard_Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard_Slot) ProtoMessage() {}

func (x *BingoCard_Slot) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard_Slot.ProtoReflect.Descriptor instead.
func (*BingoCard_Slot) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BingoCard_Slot) GetGoalName() string {
	if x != nil {
		return x.GoalName
	}
	return ""
}

func (x *BingoCard_Slot) GetGoalData() *Goal {
	if x != nil {
		return x.GoalData
	}
	return nil
}

type BingoCard_GridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*BingoCard_Slot      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BingoCard_GridRow) Reset() {
	*x = BingoCard_GridRow{}
	mi := &file_v1_totle_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BingoCard_GridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BingoCard_GridRow) ProtoMessage() {}

func (x *BingoCard_GridRow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_totle_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BingoCard_GridRow.ProtoReflect.Descriptor instead.
func (*BingoCard_GridRow) Descriptor() ([]byte, []int) {
	return file_v1_totle_tasks_proto_rawDescGZIP(), []int{1, 1}
}

func (x *BingoCard_GridRow) GetSlots() []*BingoCard_Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

var File_v1_totle_tasks_proto protoreflect.FileDescriptor

const file_v1_totle_tasks_proto_rawDesc = "" +
	"\n" +
	"\x14v1/totle_tasks.proto\x12\x0etotle_tasks.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x03\n" +
	"\x04Goal\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12$\n" +
	"\vis_assigned\x18\x04 \x01(\bB\x03\xe0A\x03R\n" +
	"isAssigned\x12?\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2\x1f.totle_tasks.v1.Goal.VisibilityR\n" +
	"visibility\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\"A\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x02:>\xeaA;\n" +
	"\x1etotletasks.googleapis.com/Goal\x12\x19users/{user}/goals/{goal}\"\xe5\x03\n" +
	"\tBingoCard\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x125\n" +
	"\x04grid\x18\x02 \x03(\v2!.totle_tasks.v1.BingoCard.GridRowR\x04grid\x12\x17\n" +
	"\x04year\x18\x03 \x01(\x05B\x03\xe0A\x05R\x04year\x12\x19\n" +
	"\x05month\x18\x04 \x01(\x05B\x03\xe0A\x05R\x05month\x12@\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x1a\x80\x01\n" +
	"\x04Slot\x12@\n" +
	"\tgoal_name\x18\x01 \x01(\tB#\xfaA \n" +
	"\x1etotletasks.googleapis.com/GoalR\bgoalName\x126\n" +
	"\tgoal_data\x18\x02 \x01(\v2\x14.totle_tasks.v1.GoalB\x03\xe0A\x03R\bgoalData\x1a?\n" +
	"\aGridRow\x124\n" +
	"\x05slots\x18\x01 \x03(\v2\x1e.totle_tasks.v1.BingoCard.SlotR\x05slots:N\xeaAK\n" +
	"#totletasks.googleapis.com/BingoCard\x12$users/{user}/bingoCards/{bingo_card}\"_\n" +
	"\x11CreateGoalRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12-\n" +
	"\x04goal\x18\x02 \x01(\v2\x14.totle_tasks.v1.GoalB\x03\xe0A\x02R\x04goal\")\n" +
	"\x0eGetGoalRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"t\n" +
	"\x19ListAvailableGoalsRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"p\n" +
	"\x1aListAvailableGoalsResponse\x12*\n" +
	"\x05goals\x18\x01 \x03(\v2\x14.totle_tasks.v1.GoalR\x05goals\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x14BatchGetGoalsRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tB\x03\xe0A\x02R\x06parent\x12\x19\n" +
	"\x05names\x18\x02 \x03(\tB\x03\xe0A\x02R\x05names\"C\n" +
	"\x15BatchGetGoalsResponse\x12*\n" +
	"\x05goals\x18\x01 \x03(\v2\x14.totle_tasks.v1.GoalR\x05goals\"\x7f\n" +
	"\x11UpdateGoalRequest\x12-\n" +
	"\x04goal\x18\x01 \x01(\v2\x14.totle_tasks.v1.GoalB\x03\xe0A\x02R\x04goal\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\",\n" +
	"\x11DeleteGoalRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"\x9f\x01\n" +
	"\x13GetBingoCardRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12<\n" +
	"\x04view\x18\x02 \x01(\x0e2(.totle_tasks.v1.GetBingoCardRequest.ViewR\x04view\"1\n" +
	"\x04View\x12\x14\n" +
	"\x10VIEW_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05BASIC\x10\x01\x12\b\n" +
	"\x04FULL\x10\x02\"\x94\x01\n" +
	"\x16UpdateBingoCardRequest\x12=\n" +
	"\n" +
	"bingo_card\x18\x01 \x01(\v2\x19.totle_tasks.v1.BingoCardB\x03\xe0A\x02R\tbingoCard\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\xf0\x03\n" +
	"\vGoalService\x12E\n" +
	"\n" +
	"CreateGoal\x12!.totle_tasks.v1.CreateGoalRequest\x1a\x14.totle_tasks.v1.Goal\x12?\n" +
	"\aGetGoal\x12\x1e.totle_tasks.v1.GetGoalRequest\x1a\x14.totle_tasks.v1.Goal\x12k\n" +
	"\x12ListAvailableGoals\x12).totle_tasks.v1.ListAvailableGoalsRequest\x1a*.totle_tasks.v1.ListAvailableGoalsResponse\x12\\\n" +
	"\rBatchGetGoals\x12$.totle_tasks.v1.BatchGetGoalsRequest\x1a%.totle_tasks.v1.BatchGetGoalsResponse\x12E\n" +
	"\n" +
	"UpdateGoal\x12!.totle_tasks.v1.UpdateGoalRequest\x1a\x14.totle_tasks.v1.Goal\x12G\n" +
	"\n" +
	"DeleteGoal\x12!.totle_tasks.v1.DeleteGoalRequest\x1a\x16.google.protobuf.Empty2\xb4\x01\n" +
	"\fBingoService\x12N\n" +
	"\fGetBingoCard\x12#.totle_tasks.v1.GetBingoCardRequest\x1a\x19.totle_tasks.v1.BingoCard\x12T\n" +
	"\x0fUpdateBingoCard\x12&.totle_tasks.v1.UpdateBingoCardRequest\x1a\x19.totle_tasks.v1.BingoCardB;Z9github.com/bibyen/totle-tasks/internal/pb/v1;totletasksv1b\x06proto3"

var (
	file_v1_totle_tasks_proto_rawDescOnce sync.Once
	file_v1_totle_tasks_proto_rawDescData []byte
)

func file_v1_totle_tasks_proto_rawDescGZIP() []byte {
	file_v1_totle_tasks_proto_rawDescOnce.Do(func() {
		file_v1_totle_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_totle_tasks_proto_rawDesc), len(file_v1_totle_tasks_proto_rawDesc)))
	})
	return file_v1_totle_tasks_proto_rawDescData
}

var file_v1_totle_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_totle_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_v1_totle_tasks_proto_goTypes = []any{
	(Goal_Visibility)(0),               // 0: totle_tasks.v1.Goal.Visibility
	(GetBingoCardRequest_View)(0),      // 1: totle_tasks.v1.GetBingoCardRequest.View
	(*Goal)(nil),                       // 2: totle_tasks.v1.Goal
	(*BingoCard)(nil),                  // 3: totle_tasks.v1.BingoCard
	(*CreateGoalRequest)(nil),          // 4: totle_tasks.v1.CreateGoalRequest
	(*GetGoalRequest)(nil),             // 5: totle_tasks.v1.GetGoalRequest
	(*ListAvailableGoalsRequest)(nil),  // 6: totle_tasks.v1.ListAvailableGoalsRequest
	(*ListAvailableGoalsResponse)(nil), // 7: totle_tasks.v1.ListAvailableGoalsResponse
	(*BatchGetGoalsRequest)(nil),       // 8: totle_tasks.v1.BatchGetGoalsRequest
	(*BatchGetGoalsResponse)(nil),      // 9: totle_tasks.v1.BatchGetGoalsResponse
	(*UpdateGoalRequest)(nil),          // 10: totle_tasks.v1.UpdateGoalRequest
	(*DeleteGoalRequest)(nil),          // 11: totle_tasks.v1.DeleteGoalRequest
	(*GetBingoCardRequest)(nil),        // 12: totle_tasks.v1.GetBingoCardRequest
	(*UpdateBingoCardRequest)(nil),     // 13: totle_tasks.v1.UpdateBingoCardRequest
	(*BingoCard_Slot)(nil),             // 14: totle_tasks.v1.BingoCard.Slot
	(*BingoCard_GridRow)(nil),          // 15: totle_tasks.v1.BingoCard.GridRow
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),      // 17: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),              // 18: google.protobuf.Empty
}
var file_v1_totle_tasks_proto_depIdxs = []int32{
	0,  // 0: totle_tasks.v1.Goal.visibility:type_name -> totle_tasks.v1.Goal.Visibility
	16, // 1: totle_tasks.v1.Goal.create_time:type_name -> google.protobuf.Timestamp
	15, // 2: totle_tasks.v1.BingoCard.grid:type_name -> totle_tasks.v1.BingoCard.GridRow
	16, // 3: totle_tasks.v1.BingoCard.update_time:type_name -> google.protobuf.Timestamp
	2,  // 4: totle_tasks.v1.CreateGoalRequest.goal:type_name -> totle_tasks.v1.Goal
	2,  // 5: totle_tasks.v1.ListAvailableGoalsResponse.goals:type_name -> totle_tasks.v1.Goal
	2,  // 6: totle_tasks.v1.BatchGetGoalsResponse.goals:type_name -> totle_tasks.v1.Goal
	2,  // 7: totle_tasks.v1.UpdateGoalRequest.goal:type_name -> totle_tasks.v1.Goal
	17, // 8: totle_tasks.v1.UpdateGoalRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 9: totle_tasks.v1.GetBingoCardRequest.view:type_name -> totle_tasks.v1.GetBingoCardRequest.View
	3,  // 10: totle_tasks.v1.UpdateBingoCardRequest.bingo_card:type_name -> totle_tasks.v1.BingoCard
	17, // 11: totle_tasks.v1.UpdateBingoCardRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 12: totle_tasks.v1.BingoCard.Slot.goal_data:type_name -> totle_tasks.v1.Goal
	14, // 13: totle_tasks.v1.BingoCard.GridRow.slots:type_name -> totle_tasks.v1.BingoCard.Slot
	4,  // 14: totle_tasks.v1.GoalService.CreateGoal:input_type -> totle_tasks.v1.CreateGoalRequest
	5,  // 15: totle_tasks.v1.GoalService.GetGoal:input_type -> totle_tasks.v1.GetGoalRequest
	6,  // 16: totle_tasks.v1.GoalService.ListAvailableGoals:input_type -> totle_tasks.v1.ListAvailableGoalsRequest
	8,  // 17: totle_tasks.v1.GoalService.BatchGetGoals:input_type -> totle_tasks.v1.BatchGetGoalsRequest
	10, // 18: totle_tasks.v1.GoalService.UpdateGoal:input_type -> totle_tasks.v1.UpdateGoalRequest
	11, // 19: totle_tasks.v1.GoalService.DeleteGoal:input_type -> totle_tasks.v1.DeleteGoalRequest
	12, // 20: totle_tasks.v1.BingoService.GetBingoCard:input_type -> totle_tasks.v1.GetBingoCardRequest
	13, // 21: totle_tasks.v1.BingoService.UpdateBingoCard:input_type -> totle_tasks.v1.UpdateBingoCardRequest
	2,  // 22: totle_tasks.v1.GoalService.CreateGoal:output_type -> totle_tasks.v1.Goal
	2,  // 23: totle_tasks.v1.GoalService.GetGoal:output_type -> totle_tasks.v1.Goal
	7,  // 24: totle_tasks.v1.GoalService.ListAvailableGoals:output_type -> totle_tasks.v1.ListAvailableGoalsResponse
	9,  // 25: totle_tasks.v1.GoalService.BatchGetGoals:output_type -> totle_tasks.v1.BatchGetGoalsResponse
	2,  // 26: totle_tasks.v1.GoalService.UpdateGoal:output_type -> totle_tasks.v1.Goal
	18, // 27: totle_tasks.v1.GoalService.DeleteGoal:output_type -> google.protobuf.Empty
	3,  // 28: totle_tasks.v1.BingoService.GetBingoCard:output_type -> totle_tasks.v1.BingoCard
	3,  // 29: totle_tasks.v1.BingoService.UpdateBingoCard:output_type -> totle_tasks.v1.BingoCard
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_totle_tasks_proto_init() }
func file_v1_totle_tasks_proto_init() {
	if File_v1_totle_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_totle_tasks_proto_rawDesc), len(file_v1_totle_tasks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1_totle_tasks_proto_goTypes,
		DependencyIndexes: file_v1_totle_tasks_proto_depIdxs,
		EnumInfos:         file_v1_totle_tasks_proto_enumTypes,
		MessageInfos:      file_v1_totle_tasks_proto_msgTypes,
	}.Build()
	File_v1_totle_tasks_proto = out.File
	file_v1_totle_tasks_proto_goTypes = nil
	file_v1_totle_tasks_proto_depIdxs = nil
}
