// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v1/totle_tasks.proto

package totletasksv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoalService_CreateGoal_FullMethodName         = "/totle_tasks.v1.GoalService/CreateGoal"
	GoalService_GetGoal_FullMethodName            = "/totle_tasks.v1.GoalService/GetGoal"
	GoalService_ListAvailableGoals_FullMethodName = "/totle_tasks.v1.GoalService/ListAvailableGoals"
	GoalService_BatchGetGoals_FullMethodName      = "/totle_tasks.v1.GoalService/BatchGetGoals"
	GoalService_UpdateGoal_FullMethodName         = "/totle_tasks.v1.GoalService/UpdateGoal"
	GoalService_DeleteGoal_FullMethodName         = "/totle_tasks.v1.GoalService/DeleteGoal"
)

// GoalServiceClient is the client API for GoalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================
// GOAL SERVICE
// Handles the lifecycle of individual tasks.
// ==========================================
type GoalServiceClient interface {
	// Creates a new goal for the user's bank.
	CreateGoal(ctx context.Context, in *CreateGoalRequest, opts ...grpc.CallOption) (*Goal, error)
	// Retrieves a specific goal by resource name.
	GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*Goal, error)
	// Lists only goals that are NOT currently assigned to any BingoCard.
	// This powers the "Available Tasks" picker in the UI.
	ListAvailableGoals(ctx context.Context, in *ListAvailableGoalsRequest, opts ...grpc.CallOption) (*ListAvailableGoalsResponse, error)
	// Retrieves multiple goals in one round-trip.
	// Used by BingoService to hydrate the grid layout.
	BatchGetGoals(ctx context.Context, in *BatchGetGoalsRequest, opts ...grpc.CallOption) (*BatchGetGoalsResponse, error)
	// Updates goal details (title, completion, etc.) using a FieldMask.
	UpdateGoal(ctx context.Context, in *UpdateGoalRequest, opts ...grpc.CallOption) (*Goal, error)
	// Deletes a goal.
	// Validation: Implementation must reject deletion if goal.is_assigned is true.
	DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type goalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoalServiceClient(cc grpc.ClientConnInterface) GoalServiceClient {
	return &goalServiceClient{cc}
}

func (c *goalServiceClient) CreateGoal(ctx context.Context, in *CreateGoalRequest, opts ...grpc.CallOption) (*Goal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Goal)
	err := c.cc.Invoke(ctx, GoalService_CreateGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*Goal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Goal)
	err := c.cc.Invoke(ctx, GoalService_GetGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) ListAvailableGoals(ctx context.Context, in *ListAvailableGoalsRequest, opts ...grpc.CallOption) (*ListAvailableGoalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableGoalsResponse)
	err := c.cc.Invoke(ctx, GoalService_ListAvailableGoals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) BatchGetGoals(ctx context.Context, in *BatchGetGoalsRequest, opts ...grpc.CallOption) (*BatchGetGoalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetGoalsResponse)
	err := c.cc.Invoke(ctx, GoalService_BatchGetGoals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) UpdateGoal(ctx context.Context, in *UpdateGoalRequest, opts ...grpc.CallOption) (*Goal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Goal)
	err := c.cc.Invoke(ctx, GoalService_UpdateGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GoalService_DeleteGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoalServiceServer is the server API for GoalService service.
// All implementations must embed UnimplementedGoalServiceServer
// for forward compatibility.
//
// ==========================================
// GOAL SERVICE
// Handles the lifecycle of individual tasks.
// ==========================================
type GoalServiceServer interface {
	// Creates a new goal for the user's bank.
	CreateGoal(context.Context, *CreateGoalRequest) (*Goal, error)
	// Retrieves a specific goal by resource name.
	GetGoal(context.Context, *GetGoalRequest) (*Goal, error)
	// Lists only goals that are NOT currently assigned to any BingoCard.
	// This powers the "Available Tasks" picker in the UI.
	ListAvailableGoals(context.Context, *ListAvailableGoalsRequest) (*ListAvailableGoalsResponse, error)
	// Retrieves multiple goals in one round-trip.
	// Used by BingoService to hydrate the grid layout.
	BatchGetGoals(context.Context, *BatchGetGoalsRequest) (*BatchGetGoalsResponse, error)
	// Updates goal details (title, completion, etc.) using a FieldMask.
	UpdateGoal(context.Context, *UpdateGoalRequest) (*Goal, error)
	// Deletes a goal.
	// Validation: Implementation must reject deletion if goal.is_assigned is true.
	DeleteGoal(context.Context, *DeleteGoalRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGoalServiceServer()
}

// UnimplementedGoalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoalServiceServer struct{}

func (UnimplementedGoalServiceServer) CreateGoal(context.Context, *CreateGoalRequest) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoal not implemented")
}
func (UnimplementedGoalServiceServer) GetGoal(context.Context, *GetGoalRequest) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoal not implemented")
}
func (UnimplementedGoalServiceServer) ListAvailableGoals(context.Context, *ListAvailableGoalsRequest) (*ListAvailableGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableGoals not implemented")
}
func (UnimplementedGoalServiceServer) BatchGetGoals(context.Context, *BatchGetGoalsRequest) (*BatchGetGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetGoals not implemented")
}
func (UnimplementedGoalServiceServer) UpdateGoal(context.Context, *UpdateGoalRequest) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoal not implemented")
}
func (UnimplementedGoalServiceServer) DeleteGoal(context.Context, *DeleteGoalRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoal not implemented")
}
func (UnimplementedGoalServiceServer) mustEmbedUnimplementedGoalServiceServer() {}
func (UnimplementedGoalServiceServer) testEmbeddedByValue()                     {}

// UnsafeGoalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoalServiceServer will
// result in compilation errors.
type UnsafeGoalServiceServer interface {
	mustEmbedUnimplementedGoalServiceServer()
}

func RegisterGoalServiceServer(s grpc.ServiceRegistrar, srv GoalServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoalService_ServiceDesc, srv)
}

func _GoalService_CreateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).CreateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_CreateGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).CreateGoal(ctx, req.(*CreateGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_GetGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetGoal(ctx, req.(*GetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_ListAvailableGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).ListAvailableGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_ListAvailableGoals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).ListAvailableGoals(ctx, req.(*ListAvailableGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_BatchGetGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).BatchGetGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_BatchGetGoals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).BatchGetGoals(ctx, req.(*BatchGetGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_UpdateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).UpdateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_UpdateGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).UpdateGoal(ctx, req.(*UpdateGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_DeleteGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).DeleteGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoalService_DeleteGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).DeleteGoal(ctx, req.(*DeleteGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoalService_ServiceDesc is the grpc.ServiceDesc for GoalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "totle_tasks.v1.GoalService",
	HandlerType: (*GoalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGoal",
			Handler:    _GoalService_CreateGoal_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _GoalService_GetGoal_Handler,
		},
		{
			MethodName: "ListAvailableGoals",
			Handler:    _GoalService_ListAvailableGoals_Handler,
		},
		{
			MethodName: "BatchGetGoals",
			Handler:    _GoalService_BatchGetGoals_Handler,
		},
		{
			MethodName: "UpdateGoal",
			Handler:    _GoalService_UpdateGoal_Handler,
		},
		{
			MethodName: "DeleteGoal",
			Handler:    _GoalService_DeleteGoal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/totle_tasks.proto",
}

const (
	BingoService_GetBingoCard_FullMethodName    = "/totle_tasks.v1.BingoService/GetBingoCard"
	BingoService_UpdateBingoCard_FullMethodName = "/totle_tasks.v1.BingoService/UpdateBingoCard"
)

// BingoServiceClient is the client API for BingoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==========================================
// BINGO SERVICE
// Handles the monthly grid arrangement and hydration.
// ==========================================
type BingoServiceClient interface {
	// Retrieves the card for a specific month (YYYY-MM).
	// Use View.FULL to populate goal_data in the response via BatchGetGoals.
	GetBingoCard(ctx context.Context, in *GetBingoCardRequest, opts ...grpc.CallOption) (*BingoCard, error)
	// Updates the grid configuration (assigning/moving goals).
	UpdateBingoCard(ctx context.Context, in *UpdateBingoCardRequest, opts ...grpc.CallOption) (*BingoCard, error)
}

type bingoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBingoServiceClient(cc grpc.ClientConnInterface) BingoServiceClient {
	return &bingoServiceClient{cc}
}

func (c *bingoServiceClient) GetBingoCard(ctx context.Context, in *GetBingoCardRequest, opts ...grpc.CallOption) (*BingoCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BingoCard)
	err := c.cc.Invoke(ctx, BingoService_GetBingoCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bingoServiceClient) UpdateBingoCard(ctx context.Context, in *UpdateBingoCardRequest, opts ...grpc.CallOption) (*BingoCard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BingoCard)
	err := c.cc.Invoke(ctx, BingoService_UpdateBingoCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BingoServiceServer is the server API for BingoService service.
// All implementations must embed UnimplementedBingoServiceServer
// for forward compatibility.
//
// ==========================================
// BINGO SERVICE
// Handles the monthly grid arrangement and hydration.
// ==========================================
type BingoServiceServer interface {
	// Retrieves the card for a specific month (YYYY-MM).
	// Use View.FULL to populate goal_data in the response via BatchGetGoals.
	GetBingoCard(context.Context, *GetBingoCardRequest) (*BingoCard, error)
	// Updates the grid configuration (assigning/moving goals).
	UpdateBingoCard(context.Context, *UpdateBingoCardRequest) (*BingoCard, error)
	mustEmbedUnimplementedBingoServiceServer()
}

// UnimplementedBingoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBingoServiceServer struct{}

func (UnimplementedBingoServiceServer) GetBingoCard(context.Context, *GetBingoCardRequest) (*BingoCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBingoCard not implemented")
}
func (UnimplementedBingoServiceServer) UpdateBingoCard(context.Context, *UpdateBingoCardRequest) (*BingoCard, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBingoCard not implemented")
}
func (UnimplementedBingoServiceServer) mustEmbedUnimplementedBingoServiceServer() {}
func (UnimplementedBingoServiceServer) testEmbeddedByValue()                      {}

// UnsafeBingoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BingoServiceServer will
// result in compilation errors.
type UnsafeBingoServiceServer interface {
	mustEmbedUnimplementedBingoServiceServer()
}

func RegisterBingoServiceServer(s grpc.ServiceRegistrar, srv BingoServiceServer) {
	// If the following call pancis, it indicates UnimplementedBingoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BingoService_ServiceDesc, srv)
}

func _BingoService_GetBingoCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBingoCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingoServiceServer).GetBingoCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BingoService_GetBingoCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingoServiceServer).GetBingoCard(ctx, req.(*GetBingoCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BingoService_UpdateBingoCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBingoCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BingoServiceServer).UpdateBingoCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BingoService_UpdateBingoCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BingoServiceServer).UpdateBingoCard(ctx, req.(*UpdateBingoCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BingoService_ServiceDesc is the grpc.ServiceDesc for BingoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BingoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "totle_tasks.v1.BingoService",
	HandlerType: (*BingoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBingoCard",
			Handler:    _BingoService_GetBingoCard_Handler,
		},
		{
			MethodName: "UpdateBingoCard",
			Handler:    _BingoService_UpdateBingoCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/totle_tasks.proto",
}
